# Generated by Django 3.1.4 on 2020-12-11 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20201211_0209'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='length',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
